name: Publish
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: true
        default: '0.0.0'
      release_name:
        description: 'Release Name'
        required: true
        default: 'draft'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with AHK v2.0.12
        uses: nukdokplex/autohotkey-build@v0.1
        with:
          version: v2.0.12
          x64: true
          x86: true
          compression: upx
          in: ""
          out: dist
          icon: /images/favicon.ico

      - name: Copy Required Files
        shell: pwsh
        run: |
          copy ".\settings.json" ".\dist\settings.json"
          copy ".\hotstrings.json" ".\dist\hotstrings.json"
          xcopy ".\images\" ".\dist\images\" /E /H /C /I
          
      - name: Zip Dist Folder
        uses: vimtor/action-zip@v1.2
        with:
          files: dist/
          dest: TagCompanion.zip
          
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '${{ github.event.inputs.tag_name }}'
          release_name: '${{ github.event.inputs.release_name }}'
          draft: true
          prerelease: false
  
      - name: Upload Build Assets
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./TagCompanion.zip
          asset_name: TagCompanion-${{ github.event.inputs.tag_name }}.zip
          asset_content_type: application/zip
  
      - name: Publish Release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
