name: Build Windows Installer
on:
  push:
  pull_request:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'Version'
        required: false
        default: 'SNAPSHOT'

  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version'
        required: false
        default: 'SNAPSHOT'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Insert Build Parameters
        run: |
          Get-ChildItem -Recurse -File | ForEach-Object { (Get-Content $_.FullName) -replace '\$\{VERSION\}', '${{ github.event.inputs.version }}' | Set-Content $_.FullName }

      - name: Build with Ahk2Exe
        uses: benmusson/ahk2exe-action@v1
        with:
          ahk-tag: v2.0.18
          in: .\TagCompanion.ahk
          out: .\TagCompanion.exe
          icon: .\images\favicon.ico
          target: x64
          compression: upx
          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Perform msbuild
        run: msbuild -nologo -restore bundle\TagCompanion.wixproj -p:Configuration=Release -p:ProductVersion=${{ github.event.inputs.version }} -p:TAGCOMPANION_BUILD=${{ github.workspace }}\.build\release -p:OutputPath=${{ github.workspace }}\artifacts -p:RunWixToolsOutOfProc=true    

      - name: Convert file name
        run: |
          Rename-Item -Path "${{ github.workspace }}\artifacts\TagCompanion.msi" -NewName "TagCompanion-${{ github.event.inputs.version }}.msi"
          $MSI_PATH = cygpath -m ${{ github.workspace }}\artifacts\TagCompanion-${{ github.event.inputs.version }}.msi
          Echo MSI_PATH=$MSI_PATH | Out-File -FilePath ${env:GITHUB_ENV} -Encoding utf8 -Append

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.event.inputs.version }}
          path: |
            .*exe