name: Windows Installer
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.0.0'
      release_name:
        description: 'Release Name'
        required: true
        default: 'draft'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with AHK v2.0.12
        uses: nukdokplex/autohotkey-build@v0.1
        with:
          version: v2.0.12
          x64: true
          compression: upx
          in: ""
          out: ""
          x64_suffix: ""
          icon: /images/favicon.ico
          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Perform msbuild
        run: msbuild -nologo -restore bundle\TagCompanion.wixproj -p:Configuration=Release -p:ProductVersion=${{ github.event.inputs.version }} -p:TAGCOMPANION_BUILD=${{ github.workspace }}\.build\release -p:OutputPath=${{ github.workspace }}\artifacts -p:RunWixToolsOutOfProc=true

      - name: Convert file name
        run: |
          $MSI_PATH = cygpath -m ${{ github.workspace }}\artifacts\TagCompanion.msi
          Echo MSI_PATH=$MSI_PATH | Out-File -FilePath ${env:GITHUB_ENV} -Encoding utf8 -Append
        
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: '${{ github.workspace }}\artifacts\TagCompanion.msi'
          tag_name: '${{ github.event.inputs.version }}'
          make_latest: true
