name: Windows Installer
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.0.0'
      release_name:
        description: 'Release Name'
        required: true
        default: 'draft'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with AHK v2.0.12
        uses: nukdokplex/autohotkey-build@v0.1
        with:
          version: v2.0.12
          x64: true
          compression: upx
          in: ""
          out: ""
          x64_suffix: ""
          icon: /images/favicon.ico
          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Install WiX
        run: |
          dotnet tool install --global wix --version 4.0.5
        
      - name: Build WiX
        run: wix build .\Installer.wxs

      - name: Rename MSI
        shell: pwsh
        run: |
          Rename-Item -Path "Installer.msi" -NewName "TagCompanion-${{ github.event.inputs.version }}.msi"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: 'TagCompanion-${{ github.event.inputs.version }}.msi'
          tag_name: 'latest'
          make_latest: true
