name: Windows Installer
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.0.0'
      release_name:
        description: 'Release Name'
        required: true
        default: 'draft'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Insert Build Parameters
        run: |
          Get-ChildItem -Recurse -File | ForEach-Object { (Get-Content $_.FullName) -replace '\$\{VERSION\}', '${{ github.event.inputs.version }}' | Set-Content $_.FullName }
          Get-ChildItem -Recurse -File | ForEach-Object { (Get-Content $_.FullName) -replace '\$\{RELEASE_NAME\}', '${{ github.event.inputs.release_name }}' | Set-Content $_.FullName }

      - name: Build with AHK v2.0.12
        uses: benmusson/ahk2exe-action@v0.1.0
        with:
          in: .\TagCompanion.ahk
          icon: .\images\favicon.ico
          out: .\TagCompanion.exe
          target: x64
          ahk-tag: v2.0.18
          compression: upx
          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Perform msbuild
        run: msbuild -nologo -restore bundle\TagCompanion.wixproj -p:Configuration=Release -p:ProductVersion=${{ github.event.inputs.version }} -p:TAGCOMPANION_BUILD=${{ github.workspace }}\.build\release -p:OutputPath=${{ github.workspace }}\artifacts -p:RunWixToolsOutOfProc=true    

      - name: Convert file name
        run: |
          Rename-Item -Path "${{ github.workspace }}\artifacts\TagCompanion.msi" -NewName "TagCompanion-${{ github.event.inputs.version }}.msi"
          $MSI_PATH = cygpath -m ${{ github.workspace }}\artifacts\TagCompanion-${{ github.event.inputs.version }}.msi
          Echo MSI_PATH=$MSI_PATH | Out-File -FilePath ${env:GITHUB_ENV} -Encoding utf8 -Append
        
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: '${{ env.MSI_PATH }}'
          tag_name: '${{ github.event.inputs.version }}'
          make_latest: true
