name: Release Windows Installer
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'SNAPSHOT'

jobs:
  build:
    uses: ./.github/workflows/build.yml 
    with:
      version: ${{ github.event.inputs.version }}
  
  release:
    runs-on: windows-latest
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-${{ github.event.inputs.version }}
          path: build-artifacts

      - name: Convert file name
        run: |
          $MSI_PATH = cygpath -m ${{ github.workspace }}\build-artifacts\TagCompanion-${{ env.VERSION }}.msi
          Echo MSI_PATH=$MSI_PATH | Out-File -FilePath ${env:GITHUB_ENV} -Encoding utf8 -Append

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: '${{env.MSI_PATH }}'
          tag_name: '${{ github.event.inputs.version }}'
          make_latest: true
